### PR TITLE
Add WeMos D1 R2 (mini) board

### PR DESCRIPTION
**Pull request by booo**
Adds the WeMos D1 R2 (mini) board to the build process. Platformio
documentation:

https://docs.platformio.org/en/latest/boards/espressif8266/d1_mini.html

### CODE REVIEW

**Comment by booo** [comment]
What's the state of this repository? Is it still maintained or should I create a pull request for another fork?

**Comment by rmackay9** [comment]
@booo, development isn't that active but I think it's still maintained.  I suspect @tridge is the one that would need to review this and he's away for a few days.

**Comment by booo** [comment]
Thanks a lot for your feedback.

The current build fails: https://travis-ci.com/github/ArduPilot/mavesp8266/builds/189684717

As far as I can see the current code was forked from https://github.com/dogmaphobic/mavesp8266/commits/master. The code from dogmaphobic builds just fine.

Do we have an interest in maintaining a fork or could we just use the original code?

Maybe we should enable tickets here so we can discuss stuff like that in a ticket?

**Review by khancyr — APPROVED** [review]
LGTM

**Pull request closed without merging**
