### PR TITLE
Do not send zero-byte packets in raw mode

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
Was this in any way related to the issue we found the other day with the user using an out-of-date ESP firmware which didn't support mavlink2?  It doesn't seem related but with no description on the PR, who knows?

**Comment by peterbarker** [comment]
@rmackay9 sorry, discussion was on Discord:
```
[11:50 AM] Peter Barker: @AndrewTridgell problem with  mavesp8266 firmware; on autopilot reboot the gateway starts spewing out vast numbers of zero-length UDP messages:
11:48:49.750300 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.751089 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.751841 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.752866 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.753811 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.754368 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.755329 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.756058 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.756962 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.757890 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.758590 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.759569 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.760377 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.761216 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.761999 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
11:48:49.762833 IP 192.168.4.1.14555 > 192.168.4.2.14550: UDP, length 0
 
[12:03 PM] 
BOT
 Bookmarker: @AndrewTridgell please change your privacy settings to Allow direct messages from server members.
[1:15 PM] Peter Barker: @AndrewTridgell 
vehicle param show 
LOITER> DEBUG_ENABLED    0
RAW_ENABLE       -1
SW_VER           16908291
.
.

    } else if(getWorld()->getParameters()->getRawEnable() && cmd->command == MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN) {
        //-- Reset "Companion Computer"
        if((uint8_t)cmd->param2 == 1) {
[1:15 PM] Peter Barker: default is "false" for RAW_ENABLE, so problem is that the value of that parameter has gotten to -1 somehow
[1:15 PM] Peter Barker: (wasn't me!  honest!)
[1:16 PM] Peter Barker: Welll... that's the first problem.  The second problem is raw-mode sending 0-byte packets.  WTF?
[1:22 PM] Peter Barker: https://github.com/ArduPilot/mavesp8266/pull/7
GitHub
Do not send zero-byte packets in raw mode by peterbarker · Pull Req...
Image
```

**Comment by rmackay9** [comment]
@peterbarker, from a user's point of view what is the impact?  Does it cause slow parameter load?  eats up bandwidth?  I see a lot of user support calls about various things so I'd like to know if possible.

**Comment by peterbarker** [comment]
On Tue, 9 Nov 2021, Randy Mackay wrote:

> @peterbarker, from a user's point of view what is the impact? Does it cause slow parameter load? eats up bandwidth? I see a lot of user support calls about various things so I'd like to know if possible.

*Extemely* intermittent telemetry is what I saw.

We should probably do another mavesp8266 release, or at least have a 
binary available for people to try.

**Pull request merged**
